In [2]:
import numpy as np

In [3]:
a = np.arange(20)

In [10]:
b = np.arange(20)

In [13]:
np.add(a,b)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [16]:
su = a[0]

In [17]:
su = np.add(a,b)

In [31]:
a = np.array([[3,4],[0,0]])

In [32]:
np.linalg.norm(a)

5.0

In [8]:
np.sum(a)

190

In [9]:
np.mean?

In [56]:
c = np.arange(6).reshape(3,2)

In [57]:
d = np.transpose(c).reshape(2,3)

In [60]:
e = np.arange(5)

In [61]:
e += 2

In [62]:
e

array([2, 3, 4, 5, 6])

In [50]:
e = np.array([5,4])[np.newaxis]
print(e)
print(e.T)

[[5 4]]
[[5]
 [4]]
