In [3]:
import numpy as np

# Let us also import plotting library
import matplotlib.pyplot as plt   
%matplotlib inline

In [27]:
array_pi = np.full(10, 3.14)

In [28]:
print(array_pi)

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [37]:
array_pi.reshape(2,5)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [40]:
array_pi.flatten()

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [41]:
x = np.zeros((4, 5, 6, 7, 8))

In [42]:
x.shape

(4, 5, 6, 7, 8)

In [43]:
print(f'Array x_int has data type {array_pi.dtype}')

Array x_int has data type float64


In [44]:
np.prod?

In [47]:
np.sum?

In [57]:
x = np.ones((3, 4, 5, 6))
x.shape
a = x[0, :, :, 3]
b = x[0, ..., 3]


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [52]:
np.allclose(a, b)

True

In [58]:
np.allclose?

In [59]:
np.trace?

In [60]:
a = np.arange(8).reshape((2,2,2))

In [61]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
x = np.random.uniform(0, 10, (5, 10, 10))



In [63]:
x

array([[[9.27419917, 7.77285909, 7.24579327, 3.60085646, 5.18449109,
         8.45720285, 6.03680877, 9.40222189, 6.48063311, 7.67408842],
        [7.07550098, 4.91280895, 6.92989483, 5.68085916, 4.35964573,
         6.73958097, 7.41366347, 9.23236282, 6.84427393, 3.30220322],
        [5.65148215, 6.0175879 , 0.96826424, 8.82573254, 2.36466846,
         9.58790175, 5.99652159, 3.09443191, 7.45015629, 4.58283852],
        [7.79918623, 4.45910612, 3.95019905, 1.85691167, 3.21613234,
         5.46368069, 2.82623644, 4.26981635, 0.73875372, 2.21699608],
        [9.28725641, 0.89299397, 6.68707799, 7.83091398, 4.25088941,
         2.15539334, 5.85888806, 1.530399  , 4.85404336, 2.78706721],
        [3.0983707 , 7.92499855, 1.97352589, 1.80209287, 9.76934979,
         3.31667454, 5.7600413 , 2.59306681, 9.67645411, 8.70004895],
        [5.43193378, 0.50206917, 8.04350913, 0.64265321, 8.54298484,
         4.46946335, 0.08925214, 7.13935336, 4.6115194 , 9.19319318],
        [7.20214539, 8.7408

In [64]:
np.trace(a)

array([6, 8])

In [71]:
x = np.trace(a, axis1=0, axis2=2)

In [72]:
x

array([5, 9])

In [73]:
np.split?

In [74]:
v1 = np.array([0.0893, 0.9332, 0.3481])
v2 = np.array([-0.6949, -0.1920, 0.6930])

In [76]:
r=v1[0]*v2[0]

In [77]:
r1=v1[1]*v2[1]

In [78]:
r2=v1[2]*v2[2]

In [79]:
r+r1+r2

4.329999999969081e-06

In [80]:
np.random.uniform?

In [81]:
np.linalg.solve?

In [83]:
 np.arange(5).reshape((-1, 1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [85]:
data = np.arange(10).reshape(2,5)

In [87]:
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
data**np.arange(np.size(data,1))

array([[   1,    1,    4,   27,  256],
       [   1,    6,   49,  512, 6561]])

In [91]:
np.zeros?

In [92]:
np.prod?

In [1]:
argmin?

Object `argmin` not found.


In [2]:
np.argmin?

Object `np.argmin` not found.


x = np.arange(11)

In [5]:
u = 5

In [6]:
np.mod(x-u)

NameError: name 'x' is not defined

In [7]:
np.mod?

In [8]:
np.mean?

In [9]:
np.std?

In [10]:
np.random.shuffle?

In [11]:
x = np.arange(10)

In [16]:
np.random.shuffle(x)

In [17]:
x

array([2, 9, 4, 1, 8, 5, 6, 3, 0, 7])

In [25]:
np.random.randint(5,88)

87

In [26]:
np.random.uniform?

In [31]:
y = np.random.uniform(0,5,(20,3,4))

In [32]:
y

array([[[0.70073216, 3.93762378, 4.33602702, 4.3549368 ],
        [4.45122202, 2.55658079, 3.18705393, 1.86507028],
        [1.62926883, 1.6023584 , 3.21086226, 3.47443351]],

       [[4.15329758, 4.73726861, 3.4208663 , 0.82310731],
        [3.88821531, 1.41553608, 4.89231976, 2.13895672],
        [2.97873115, 0.75475743, 2.20210571, 4.93572544]],

       [[3.19058744, 3.82525798, 1.30727453, 1.62818182],
        [4.65416697, 0.1619767 , 4.88294322, 4.86436722],
        [2.05096998, 4.59772585, 4.36918459, 4.95513694]],

       [[0.48875132, 1.69500414, 3.9093365 , 0.7983396 ],
        [4.48778338, 3.45833241, 0.33641137, 0.56908645],
        [0.71528006, 3.91003617, 2.55902337, 3.6624547 ]],

       [[1.68527543, 0.31828901, 1.44290388, 4.26035123],
        [3.51380836, 4.4838784 , 2.73365189, 2.85309619],
        [1.86797543, 2.79817328, 1.91190454, 0.75467635]],

       [[1.53241235, 4.17699103, 0.53920293, 3.45675011],
        [3.07323223, 0.84741618, 3.25401867, 1.14905402],
    

In [39]:
np.random.randn?

In [37]:
z = np.random.randn(5,4,3)

In [38]:
z

array([[[-0.40165791, -0.89833838, -0.29832773],
        [-1.42186619, -1.60011263,  0.25522645],
        [ 1.5500739 ,  0.70227928,  0.43849275],
        [ 2.01364105,  0.40854482,  1.64852275]],

       [[ 0.41232324,  0.72203966, -0.62797392],
        [ 0.30329545,  0.29214301, -0.05301027],
        [ 1.17324584,  0.75962134, -0.27609316],
        [ 1.29335146, -0.19448203, -1.73743556]],

       [[ 1.84500894,  0.33668144,  0.02070007],
        [-0.40208832,  0.05796652, -0.54746127],
        [ 0.17934478, -0.46235998, -0.70569952],
        [ 0.41522372, -1.11242727, -0.02827958]],

       [[-1.30317009, -0.9903229 , -0.55330484],
        [-1.2088058 ,  1.81701817,  0.15900544],
        [ 2.70764611,  0.05923587,  1.02626072],
        [-1.020821  ,  0.31354232, -0.38775343]],

       [[ 2.28446967, -1.8623658 ,  0.63987541],
        [ 0.12570578,  1.39017684, -0.29033379],
        [-0.2887827 , -0.80566892, -0.8805613 ],
        [-1.85935825, -0.05199329,  0.0834293 ]]])

In [41]:
np.random.permutation?

In [64]:
arr = np.arange(9).reshape((3, 3))

In [65]:
np.random.shuffle(arr[2])

In [66]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [7, 8, 6]])

In [67]:
np.list?

Object `np.list` not found.


In [68]:
list?

In [69]:
x = np.arange(30)

In [73]:
np.join?

Object `np.join` not found.


In [78]:
list(range(5))*3

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]